<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Checker.Application\Checker.Application.csproj" />
    <ProjectReference Include="..\Checker.Domain\Checker.Domain.csproj" />
  </ItemGroup>

</Project>
